apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-sampling-strategies
  namespace: tutorial-application
data:
  jaeger-sampling-strategies.json: |
    {
      "default_strategy": {
        "type": "probabilistic",
        "param": 1.0
      },
      "service_strategies": [
        {
          "service": "frontend-deployment",
          "type": "probabilistic",
          "param": 1.0,
          "operation_strategies": [
            {
              "operation": "GET /health",
              "type": "probabilistic",
              "param": 0.0
            }
          ]
        }
      ]
    }
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: tutorial-application
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.147.0
  mode: deployment
  env:
    - name: OTEL_K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: OTEL_K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  volumes:
    - name: jaeger-sampling-strategies
      configMap:
        name: jaeger-sampling-strategies
  volumeMounts:
    - name: jaeger-sampling-strategies
      mountPath: /etc/otelcol
  ports:
    - port: 8888
      protocol: TCP
      name: metrics
    - port: 5778
      protocol: TCP
      name: jaeger-sampling
  config:
    extensions:
      jaegerremotesampling:
        source:
          reload_interval: 30s
          file: /etc/otelcol/jaeger-sampling-strategies.json

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch: {}
      probabilistic_sampler:
        mode: equalizing
        sampling_percentage: 50

      filter/drop-debug-logs:
        error_mode: ignore
        logs:
          log_record:
            - severity_number < 9
      filter/drop-large-logs:
        error_mode: ignore
        logs:
          log_record:
            - Len(body.string) > 1000
      filter/drop-health-spans:
        error_mode: ignore
        traces:
          span:
            - attributes["http.route"] == "/health"

    connectors:
      count:
        spans:
          telemetry.spans.count:
            description: "Span count per service"
            attributes:
              - key: service.name
              - key: k8s.namespace.name
          telemetry.spans.health:
            description: "Spans from health endpoint"
            conditions:
              - attributes["http.route"] == "/health"
            attributes:
              - key: service.name
              - key: k8s.namespace.name
          telemetry.spans.attributes10:
            description: "Spans with more than 10 attributes"
            conditions:
              - Len(attributes) > 10
            attributes:
              - key: service.name
              - key: k8s.namespace.name
          telemetry.spans.dropped_attributes:
            description: "Spans with dropped attributes"
            conditions:
              - dropped_attributes_count > 0
            attributes:
              - key: service.name
              - key: k8s.namespace.name
        logs:
          telemetry.logs.count:
            description: "Log count per service"
            attributes:
              - key: service.name
              - key: k8s.namespace.name
          telemetry.logs.attributes10:
            description: "logs with more than 10 attributes"
            conditions:
              - Len(attributes) > 10
            attributes:
              - key: service.name
              - key: k8s.namespace.name
          telemetry.logs.body1000:
            description: "Log records with body larger than 1000 bytes"
            conditions:
              - Len(body.string) > 1000
            attributes:
              - key: service.name
              - key: k8s.namespace.name
          telemetry.logs.debug:
            description: "Debug log records"
            conditions:
              - severity_number < 9
            attributes:
              - key: service.name
              - key: k8s.namespace.name
        datapoints:
          telemetry.metrics.count:
            description: "Metric data point count per service"
            attributes:
              - key: service.name
              - key: k8s.namespace.name
          telemetry.metrics.attributes5:
            description: "metric data points with more than 5 attributes"
            conditions:
              - Len(attributes) > 5
            attributes:
              - key: service.name
              - key: k8s.namespace.name
          telemetry.metrics.attributes10:
            description: "metric data points with more than 10 attributes"
            conditions:
              - Len(attributes) > 10
            attributes:
              - key: service.name
              - key: k8s.namespace.name
          telemetry.metrics.resourceattributes5:
            description: "metric data points with more than 5 resource attributes"
            conditions:
              - Len(resource.attributes) > 5
            attributes:
              - key: service.name
              - key: k8s.namespace.name
          telemetry.metrics.resourceattributes10:
            description: "metric data points with more than 10 resource attributes"
            conditions:
              - Len(resource.attributes) > 10
            attributes:
              - key: service.name
              - key: k8s.namespace.name

    exporters:
      otlp_grpc:
        endpoint: otel-collector.observability-backend.svc.cluster.local:4317
        tls:
          insecure: true

      debug:
        verbosity: basic
      debug/logs:
        verbosity: detailed

    service:
#      extensions: [jaegerremotesampling]
      telemetry:
        resource:
          k8s.pod.name: ${env:OTEL_K8S_POD_NAME}
          k8s.namespace.name: ${env:OTEL_K8S_NAMESPACE}
        metrics:
          level: detailed
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
            - periodic:
                exporter:
                  otlp:
                    protocol: grpc
                    endpoint: otel-collector.observability-backend.svc.cluster.local:4320
                    insecure: true
      pipelines:
        traces:
          receivers:
           - otlp
          processors:
#            - filter/drop-health-spans
#            - probabilistic_sampler
            - batch
          exporters:
           - otlp_grpc
           -  debug
           -  count
        metrics:
          receivers:
           - otlp
          processors:
           - batch
          exporters:
            - otlp_grpc
            - debug
            - count
        metrics/count:
          receivers:
            - count
          processors:
            - batch
          exporters:
            - otlp_grpc
        logs:
          receivers:
            - otlp
          processors:
#            - filter/drop-debug-logs
#            - filter/drop-large-logs
#            - probabilistic_sampler
            - batch
          exporters:
            - otlp_grpc
            - debug/logs
            - count
