apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen-deployment
  namespace: tutorial-application
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: loadgen
        image: curlimages/curl:latest
        env:
          - name: URL
            value: "http://frontend-service:4000/"
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              #BATCH=$(( ($(od -An -tu4 -N4 /dev/urandom | tr -d ' ') % 5) + 1 )) # up to 5 req/s
              BATCH=$(( ($(od -An -tu4 -N4 /dev/urandom | tr -d ' ') % 41) + 10 )) # ~ 10-50 req/s
              #BATCH=50
              for i in $(seq 1 $BATCH); do
                PLAYERS=$(printf 'Pavol\nBenedikt\nYuri\nKristina\nSeverin' | shuf)
                P1=$(echo "$PLAYERS" | sed -n '1p')
                P2=$(echo "$PLAYERS" | sed -n '2p')
                P3=$(echo "$PLAYERS" | sed -n '3p')
                timeout 5 curl -s "${URL}?player1=${P1}&player2=${P2}&player3=${P3}" > /dev/null &
              done
              sleep 1
            done
